language: minimal
dist: xenial
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
    - make
env:
  global:
  - secure: jERHPYIwjKrPTqDF+6Xo6ztCrxN3+jRjGvrVJv2pywYCFKX+7VFLq9ANa+fSKk1EufWzk5AnNPgF7vOUjtvvVnsVW9YCHQSf2KOYn5+fX5NnAVEq7YcDWMLd8XH0mLiaTr+vR1jvJG/UB4Kf5Ashjug/b6DYAok/qrPNyCT81GL/GKvOwKXNp5voK0h+L9jeM7H6Rut19Myhz+1MXGNGWCekxbsii3s2Fp9Wu8xCk91mNTZKbbiO8vtPxmBPlsJuI41eydoruQjszTwUFcdKHxfkdYcYRY2AMYDZfI7tJZwFguarTsHAjb3WCVPmK5/wNUz6Pp2YGLH/2iwdF5s3qLGWNl2YyyttrXMEg6/h9XmWlYyak+zrg/gatNq45/hlYIlZEhsfZP8Vp8/mv6cLDNMHt4yhh4ibiSDRDKZB5i7NOlft8W81vieZ6E9RNoDlT/Ry9uFWudiHFsTKKR6HFDu8lDdFP9tDB/uOxWypz0bUp4hb8lPtqpIYXRUvFXg1QSFhOLHboGSZGoVmlYIz33wG5OjDJkm1f/6Xv67DstIpfviimOTsuQM/4ujoiFmmuYrhalFZ/bhq80XpTeLNYHlnbgyUzgHrHYx8sA8TPU2eN38ItTttNjP2HKBWHgn10n0y4uRlUsrPnlhQalSS+ndagEkNOx7PhkX4x56xlWg=
  - secure: uZSwKjy2xJ16rSikj4R8rxqm3Hn/ieuY9yJXZYgFXhgZATZnWCYKjcUQrjv9SJVNEhrn2GqdHOhIHFVTKTgEM+mQlz2OAraNHaQ3ZUYgnTkSvDPWJdH5biZC4r/BvNDF+EFRFevrojITeDtK++6iF8QnF7LGtj52951taxql9mUwnMv+WO+NPVH7eH2vPhyhWCbKOxqr7C8n+84dDOtEbcyFhTIjqCgAx4GL8q4jwk4FzfD5MB7aiRQ4iAANHRyoVhiRH/tUbhI6AmrO8ulZrM2RvZ5Yxg/ZYdUU3rK1TRhFYZtWqSPuEvVQeq4oMExhR4AxpaBH0MqJCbn/ph8G7RrzDnq/GixlK/90IAPRojcDQCWjQsvaGjOc/6Lbiy2+42Q1gGZ02DT3wiNJBHm5BujChR/wy3wnuhWvp0UPAvRaWpBbjelZBEKocenzi1sUF2nFD0x8AWnST9aSxyCimW15oVfTsB6wCE1TPAfGDDthsElZLgVYTyje66v469EZoGcGDaD8sVCst1BiWpoMcRy6+3CpPAAhBhfSQdAIiblUGtIhYcoNUBqGNMyxJdSEG49uX8nq1PSRpUUCwgNAzkOpb5oU2ZQRHWBdmktF8w3/2kXWFytbDWsrv+13Yf4SsQkMdW9amV0Z5IrimFcl9olySVKXNPBdj6fSORubdLs=
deploy:
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script: "docker login -u ${SIXSQ_DOCKER_USERNAME} -p ${SIXSQ_DOCKER_PASSWORD} && make all"
arch:
  - amd64
  - arm64
notifications:
  slack:
    secure: DfTAdZHeNd25Rc9HOoz96TCB4czcjuFdjxwPrEHoMGubKsfOvPSFNUMAEGYLx0LJGtdsCJ30fwnd5xidfI+hCIeAoxUk5t/ALbozuAd3JN8NwIQ1/1geQS9UUfXquaha6720fuG+tt2pXTHXSSGckSqg80TH9qJoM5WOsbAAfB6qKuL+5BYp5tpXJvfkG4KsOv3blbck1HKuz+8wN82aUt9vsnN+it3CChBeWM1TH/hHFUxF678ckdJFZGV2qWb8q0dEI5cWV3LMTNpmN1lUV2mTGUlCeUucoCvhzo1nSoDXL38jqn2viME9KjZNl/MHjC6kzPfe+qMxDnqLrgnTo233gI63yZwgD8w/XtgzPj3aA5gysN8KuXzWM0c2WHAApPxJCXjmZWczd5fQTmrEc2oEk8WPBe6trepKPAtIR3dA1yabYPr7+CvGV9CjhGFMv3nVE+2N1pYY0XndK8NeXIPhvzoHZv9cTTuaCSeYUmygiNY5sjCjm4FFW/Dwisdp+x/wYOesTC2q5U3X9uHTXVz2nu531Yu63YhDhQ6vIUcyfCmsJq/CShSM9xxtaPBopl1ITu04VG7S1jmD4Q3Q8oS20DMREuIZGVe1UoEG54Iq9v10uLQiXrkcvgCbNO2Nw5YdFURfA6Q13JhVGChvfA3kofHK7vyROYfNoRAmcw4=
