# This is a basic workflow to help you get started with Actions

name: 'Img Authz Plugin CI'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: armv7
            distro: buster

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run on architecture
        # You may pin to the exact commit or the version.
        # uses: uraimo/run-on-arch-action@8ba35c58b811bc0d772e45c56c38b09fbd1a0c44
        uses: uraimo/run-on-arch-action@v2.0.4
        with:
          # CPU architecture: armv6, armv7, aarch64, s390x, ppc64le.
          arch: ${{ matrix.arch }}
          # Linux distribution name: ubuntu16.04, ubuntu18.04, ubuntu20.04, buster, stretch, jessie, fedora_latest, alpine_latest.
          distro: ${{ matrix.distro }}
          # Your GitHub token, used for caching Docker images in your project's public package registry. Usually this would just be $\{{ github.token }}. This speeds up builds and is highly recommended.
          githubToken: ${{ github.token }}

          # Mount the docker socket
          dockerRunArgs: |
            --volume "/var/run/docker.sock:/var/run/docker.sock"

          install: |
                apt-get update -q -y
                apt-get install -q -y make  \
                                               apt-transport-https \
                                               ca-certificates \
                                               curl \
                                               gnupg-agent \
                                               software-properties-common \
                                               wget
                wget -O docker.tgz "https://download.docker.com/linux/static/stable/armhf/docker-19.03.12.tgz"
                tar --extract --file docker.tgz --strip-components 1 --directory /usr/local/bin/

          # Shell commands to execute in the container.
          run: echo ${{ github.SIXSQ_DOCKER_USERNAME }} && docker login -u ${{ github.SIXSQ_DOCKER_USERNAME }} -p ${{ github.SIXSQ_DOCKER_PASSWORD }} && make all

  notify:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          icon_emoji: ':eve:'
