# This is a basic workflow to help you get started with Actions

name: 'Img Authz Plugin CI'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: armv7
            distro: buster

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run on architecture
        # You may pin to the exact commit or the version.
        # uses: uraimo/run-on-arch-action@8ba35c58b811bc0d772e45c56c38b09fbd1a0c44
        uses: uraimo/run-on-arch-action@v2.0.4
        with:
          # CPU architecture: armv6, armv7, aarch64, s390x, ppc64le.
          arch: ${{ matrix.arch }}
          # Linux distribution name: ubuntu16.04, ubuntu18.04, ubuntu20.04, buster, stretch, jessie, fedora_latest, alpine_latest.
          distro: ${{ matrix.distro }}
          # Your GitHub token, used for caching Docker images in your project's public package registry. Usually this would just be $\{{ github.token }}. This speeds up builds and is highly recommended.
          githubToken: ${{ github.token }}

          # Mount the docker socket
          dockerRunArgs: --privileged -v /var/run/docker.sock:/var/run/docker.sock

          install: |
            apt-get update -q -y
            apt-get install -q -y make apt-transport-https ca-certificates curl gnupg-agent software-properties-common

            curl -fsSLk https://download.docker.com/linux/debian/gpg | apt-key add -
            add-apt-repository    "deb [arch=armhf] https://download.docker.com/linux/debian \
                      $(lsb_release -cs) \
                      stable"

            apt-get update -q -y && apt-get install -q -y docker-ce docker-ce-cli containerd.io
          # Shell commands to execute in the container.
          run: |
            sh -c "dockerd &"

            until docker ps
            do
              echo "INFO: waiting for dockerd..."
              sleep 2
            done

            set -x
            arch
            uname -a

            cat <<EOF | sudo tee /root/fake-cpuinfo
            processor	: 0
            model name	: ARMv7 Processor rev 4 (v7l)
            BogoMIPS	: 38.40
            Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
            CPU implementer	: 0x41
            CPU architecture: 7
            CPU variant	: 0x0
            CPU part	: 0xd03
            CPU revision	: 4

            processor	: 1
            model name	: ARMv7 Processor rev 4 (v7l)
            BogoMIPS	: 38.40
            Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
            CPU implementer	: 0x41
            CPU architecture: 7
            CPU variant	: 0x0
            CPU part	: 0xd03
            CPU revision	: 4

            processor	: 2
            model name	: ARMv7 Processor rev 4 (v7l)
            BogoMIPS	: 38.40
            Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
            CPU implementer	: 0x41
            CPU architecture: 7
            CPU variant	: 0x0
            CPU part	: 0xd03
            CPU revision	: 4

            processor	: 3
            model name	: ARMv7 Processor rev 4 (v7l)
            BogoMIPS	: 38.40
            Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
            CPU implementer	: 0x41
            CPU architecture: 7
            CPU variant	: 0x0
            CPU part	: 0xd03
            CPU revision	: 4

            Hardware	: BCM2709
            Revision	: a02082
            Serial		: 0000000000000000
            EOF

            mount -v --bind /root/fake-cpuinfo /proc/cpuinfo

            export DOCKER_BUILDKIT=1
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker login -u ${{ secrets.SIXSQ_DOCKER_USERNAME }} -p ${{ secrets.SIXSQ_DOCKER_PASSWORD }}
            make all

  notify:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          icon_emoji: ':ghost:'
